---
ID: "de2ebb7e-c355-465b-8f69-7fa6a4cee324"
Parent: "7e58339c-dd2a-4ecd-b045-d57d8994e486"
Template: "4a6a7e36-2481-438f-a9ba-0453ecc638fa"
Path: /sitecore/system/Marketing Control Panel/Profiles/Gender/Pattern Cards/default
DB: master
Languages:
- Language: en
  Fields:
  - ID: "fe732790-2ddb-4657-a882-c2fce1fbf0c9"
    Hint: Name
    Value: default
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181109T035541Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "124fbd07-9627-44a6-ac00-c1b3bfe62b29"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190820T161639Z
