apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fitness.name" . }}
    chart: {{ template "fitness.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "fitness.name" . }}-app
    release: {{ quote .Release.Name }}
    component: server  
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP