apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fitness.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fitness.name" . }}
    chart: {{ template "fitness.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fitness.name" . }}-app
      release: {{ quote .Release.Name }}
      component: server
  template:
    metadata:
      labels:
        app: {{ template "fitness.name" . }}-app
        release: {{ .Release.Name }}
        component: server  
    spec:
      serviceAccountName: {{ template "fitness.fullname" . }}-app
      nodeSelector:
{{ toYaml .Values.app.nodeSelector | trim | indent 8 }}
      containers:
      - name: app
        image: {{ .Values.app.image }}
        imagePullPolicy: {{ .Values.app.imagePullPolicy }}
        ports:
          - name: http
            containerPort: 80
        resources:
          limits:
            cpu: {{ .Values.app.resources.limits.cpu }}
            memory: {{ .Values.app.resources.limits.memory }}
          requests:
            cpu: {{ .Values.app.resources.requests.cpu }}
            memory: {{ .Values.app.resources.requests.memory }}
        env:
          - name: JSS_APIHOST_URL
            value: {{ .Values.global.ingress.host.cd }}
