apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fitness.fullname" . }}-cd
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fitness.name" . }}
    chart: {{ template "fitness.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fitness.name" . }}-cd
      release: {{ quote .Release.Name }}
      component: server
  template:
    metadata:
      labels:
        app: {{ template "fitness.name" . }}-cd
        release: {{ .Release.Name }}
        component: server  
    spec:
      serviceAccountName: {{ template "fitness.fullname" . }}-cd
      nodeSelector:
{{ toYaml .Values.cd.nodeSelector | trim | indent 8 }}
      containers:
      - name: cd
        image: {{ .Values.cd.image }}
        imagePullPolicy: {{ .Values.cd.imagePullPolicy }}
        ports:
          - name: http
            containerPort: 80
        resources:
          limits:
            cpu: {{ .Values.cd.resources.limits.cpu }}
            memory: {{ .Values.cd.resources.limits.memory }}
          requests:
            cpu: {{ .Values.cd.resources.requests.cpu }}
            memory: {{ .Values.cd.resources.requests.memory }}
        livenessProbe:
          initialDelaySeconds: {{ .Values.cd.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.cd.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.cd.probes.liveness.timeoutSeconds }}
          httpGet:
            scheme: "HTTP"
            path: /healthz
            port: 80
        readinessProbe:
          initialDelaySeconds: {{ .Values.cd.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.cd.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.cd.probes.readiness.timeoutSeconds }}
          httpGet:
            scheme: "HTTP"
            path: /readiness
            port: 80
        env:
          - name: APPLICATION_INSIGHTS_KEY  
            valueFrom:
              secretKeyRef:
                name: {{ template "fitness.fullname" . }}-secret
                key: ApplicationInsightsKey
          - name: SITECORE_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "fitness.fullname" . }}-secret
                key: SitecoreSqlUsername
          - name: SITECORE_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fitness.fullname" . }}-secret
                key: SitecoreSqlPassword
