apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fitness.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fitness.name" . }}
    chart: {{ template "fitness.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  SqlServerSaPassword: {{ .Values.global.secrets.SqlServerSaPassword | b64enc | quote }}
  SitecoreSqlUsername: {{ .Values.global.secrets.SitecoreSqlUsername | b64enc | quote }}
  SitecoreSqlPassword: {{ .Values.global.secrets.SitecoreSqlPassword | b64enc | quote }}
  SitecoreAdminUsername: {{ .Values.global.secrets.SitecoreAdminUsername | b64enc | quote }}
  SitecoreAdminPassword: {{ .Values.global.secrets.SitecoreAdminPassword | b64enc | quote }}
  ApplicationInsightsKey: {{ .Values.global.secrets.ApplicationInsightsKey | b64enc | quote }}
  