apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "fitness.fullname" . }}-solrdata
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fitness.name" . }}
    chart: {{ template "fitness.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.solr.storage.className }}
  resources:
    requests:
      storage: {{ .Values.solr.storage.size }}