apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fitness.fullname" . }}-xconnect
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fitness.name" . }}
    chart: {{ template "fitness.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fitness.name" . }}-xconnect
      release: {{ quote .Release.Name }}
      component: server
  template:
    metadata:
      labels:
        app: {{ template "fitness.name" . }}-xconnect
        release: {{ .Release.Name }}
        component: server  
    spec:
      serviceAccountName: {{ template "fitness.fullname" . }}-xconnect
      nodeSelector:
{{ toYaml .Values.xconnect.nodeSelector | trim | indent 8 }}
      containers:
      - name: xconnect
        image: {{ .Values.xconnect.image }}
        imagePullPolicy: {{ .Values.xconnect.imagePullPolicy }}
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
        resources:
          limits:
            cpu: {{ .Values.xconnect.resources.limits.cpu }}
            memory: {{ .Values.xconnect.resources.limits.memory }}
          requests:
            cpu: {{ .Values.xconnect.resources.requests.cpu }}
            memory: {{ .Values.xconnect.resources.requests.memory }}
        env:
          - name: APPLICATION_INSIGHTS_KEY  
            valueFrom:
              secretKeyRef:
                name: {{ template "fitness.fullname" . }}-secret
                key: ApplicationInsightsKey
          - name: SITECORE_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "fitness.fullname" . }}-secret
                key: SitecoreSqlUsername
          - name: SITECORE_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fitness.fullname" . }}-secret
                key: SitecoreSqlPassword

