apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fitness.fullname" . }}-xconnect-indexworker
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fitness.name" . }}
    chart: {{ template "fitness.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fitness.name" . }}-xconnect-indexworker
      release: {{ quote .Release.Name }}
      component: server
  template:
    metadata:
      labels:
        app: {{ template "fitness.name" . }}-xconnect-indexworker
        release: {{ .Release.Name }}
        component: server  
    spec:
      serviceAccountName: {{ template "fitness.fullname" . }}-xconnect-indexworker
      nodeSelector:
{{ toYaml .Values.xconnectIndexWorker.nodeSelector | trim | indent 8 }}
      containers:
      - name: xconnect-indexworker
        image: {{ .Values.xconnectIndexWorker.image }}
        imagePullPolicy: {{ .Values.xconnectIndexWorker.imagePullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.xconnectIndexWorker.resources.limits.cpu }}
            memory: {{ .Values.xconnectIndexWorker.resources.limits.memory }}
          requests:
            cpu: {{ .Values.xconnectIndexWorker.resources.requests.cpu }}
            memory: {{ .Values.xconnectIndexWorker.resources.requests.memory }}
        env:
          - name: APPLICATION_INSIGHTS_KEY  
            valueFrom:
              secretKeyRef:
                name: {{ template "fitness.fullname" . }}-secret
                key: ApplicationInsightsKey
          - name: SITECORE_SQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "fitness.fullname" . }}-secret
                key: SitecoreSqlUsername
          - name: SITECORE_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fitness.fullname" . }}-secret
                key: SitecoreSqlPassword

