apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fitness.fullname" . }}-xconnect
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fitness.name" . }}
    chart: {{ template "fitness.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}