{{- if .Values.nginxingress.controller.service.enableHttps }}
apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ingress.name" . }}
    chart: {{ template "ingress.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certificate | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
{{- end }}