---
ID: "90a8c208-d34c-57bf-9e0f-1c167a37b16e"
Parent: "0b05fdde-e167-55d2-b5ad-8cf27a627a0c"
Template: "0b05fdde-e167-55d2-b5ad-8cf27a627a0c"
Path: /sitecore/templates/Project/habitatfitness/PersonalDataForm/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181024T200342Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
